import Foundation

struct BotConfig {
    var botToken: String = ""
    var opencodeModel: String = ""
    var opencodeVariant: String = "medium"
    var opencodePermissionMode: String = "ask"
    var opencodeWorkdir: String = ""
    var stateFile: String = ""
    var pollTimeout: Int = 30
    var pollRetryDelay: Int = 1500
    var opencodeTimeout: Int = 600000
    var deleteWebhookOnStart: Bool = true
    var skipPendingUpdates: Bool = true
    var allowGroups: Bool = false
    var port: Int = 3000
    var webhookPath: String = "/webhook"

    static func parse(from content: String) -> BotConfig {
        var config = BotConfig()
        let lines = content.components(separatedBy: .newlines)
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard !trimmed.hasPrefix("#"), trimmed.contains("=") else { continue }
            let parts = trimmed.split(separator: "=", maxSplits: 1)
            guard parts.count == 2 else { continue }
            let key = String(parts[0]).trimmingCharacters(in: .whitespaces)
            let value = String(parts[1]).trimmingCharacters(in: .whitespaces)

            switch key {
            case "BOT_TOKEN": config.botToken = value
            case "OPENCODE_MODEL": config.opencodeModel = value
            case "OPENCODE_VARIANT": config.opencodeVariant = value
            case "OPENCODE_PERMISSION_MODE": config.opencodePermissionMode = value
            case "OPENCODE_WORKDIR": config.opencodeWorkdir = value
            case "STATE_FILE": config.stateFile = value
            case "TELEGRAM_POLL_TIMEOUT_SECONDS": config.pollTimeout = Int(value) ?? 30
            case "TELEGRAM_POLL_RETRY_DELAY_MS": config.pollRetryDelay = Int(value) ?? 1500
            case "OPENCODE_TIMEOUT_MS": config.opencodeTimeout = Int(value) ?? 600000
            case "DELETE_WEBHOOK_ON_START": config.deleteWebhookOnStart = value.lowercased() == "true"
            case "TELEGRAM_SKIP_PENDING_UPDATES_ON_START": config.skipPendingUpdates = value.lowercased() == "true"
            case "TELEGRAM_ALLOW_GROUPS": config.allowGroups = value.lowercased() == "true"
            case "PORT": config.port = Int(value) ?? 3000
            case "TELEGRAM_WEBHOOK_PATH": config.webhookPath = value
            default: break
            }
        }
        return config
    }

    func toEnvString() -> String {
        var lines: [String] = []
        lines.append("# OpenFox Configuration")
        lines.append("# Generated by OpenFox.app\n")

        lines.append("# Telegram Bot Token (required)")
        lines.append("BOT_TOKEN=\(botToken)\n")

        if !opencodeModel.isEmpty {
            lines.append("# AI Model (e.g. lm-studio/llama2)")
            lines.append("OPENCODE_MODEL=\(opencodeModel)\n")
        }

        lines.append("# Thinking variant: low, medium, high")
        lines.append("OPENCODE_VARIANT=\(opencodeVariant)\n")

        lines.append("# Permission mode: ask or allow")
        lines.append("OPENCODE_PERMISSION_MODE=\(opencodePermissionMode)\n")

        if !opencodeWorkdir.isEmpty {
            lines.append("OPENCODE_WORKDIR=\(opencodeWorkdir)")
        }
        if !stateFile.isEmpty {
            lines.append("STATE_FILE=\(stateFile)")
        }

        lines.append("\n# Polling Settings")
        lines.append("TELEGRAM_POLL_TIMEOUT_SECONDS=\(pollTimeout)")
        lines.append("TELEGRAM_POLL_RETRY_DELAY_MS=\(pollRetryDelay)")
        lines.append("OPENCODE_TIMEOUT_MS=\(opencodeTimeout)\n")

        lines.append("# Startup Behavior")
        lines.append("DELETE_WEBHOOK_ON_START=\(deleteWebhookOnStart)")
        lines.append("TELEGRAM_SKIP_PENDING_UPDATES_ON_START=\(skipPendingUpdates)")
        lines.append("TELEGRAM_ALLOW_GROUPS=\(allowGroups)\n")

        lines.append("# Webhook Settings")
        lines.append("PORT=\(port)")
        lines.append("TELEGRAM_WEBHOOK_PATH=\(webhookPath)")

        return lines.joined(separator: "\n") + "\n"
    }

    var maskedToken: String {
        guard botToken.count > 10 else { return String(repeating: "*", count: botToken.count) }
        let prefix = String(botToken.prefix(4))
        let suffix = String(botToken.suffix(4))
        return "\(prefix)...\(suffix)"
    }
}
